## Real experiments for head movements

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
%matplotlib inline

In [19]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score,f1_score
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC,LinearSVC
from sklearn.dummy import DummyClassifier
from seqlearn.perceptron import StructuredPerceptron
import sklearn_crfsuite
from sklearn_crfsuite import metrics as skcrfmetrics
from scipy.stats import pearsonr,spearmanr

In [20]:
import glob

In [21]:
windowsize="9-11-13"
memory="middle"

PATH = "C:\\Users\\zgk261\\nomco\\"+windowsize+"\\"+memory+"\\"
PATH

'C:\\Users\\zgk261\\nomco\\9-11-13\\middle\\'

In [22]:
!dir /B C:\Users\zgk261\nomco\9-11-13\middle\

F2_M4-all-final2_primary_F2.T-Tilt-ST-SideTurn-HO-HeadOther-S-Shake-W-Waggle-N-Nod-J-Jerk-HB-HeadBackward-HF-HeadForward--rdXY.svm.9-11-13-middle.tab
F2_M4-all-final2_primary_M4.T-Tilt-ST-SideTurn-HO-HeadOther-S-Shake-W-Waggle-N-Nod-J-Jerk-HB-HeadBackward-HF-HeadForward--rdXY.svm.9-11-13-middle.tab
F3_F6-all-final2_primary_F3.T-Tilt-ST-SideTurn-HO-HeadOther-S-Shake-W-Waggle-N-Nod-J-Jerk-HB-HeadBackward-HF-HeadForward--rdXY.svm.9-11-13-middle.tab
F3_F6-all-final2_primary_F6.T-Tilt-ST-SideTurn-HO-HeadOther-S-Shake-W-Waggle-N-Nod-J-Jerk-HB-HeadBackward-HF-HeadForward--rdXY.svm.9-11-13-middle.tab
F4_F1-all-final2_primary_F1.T-Tilt-ST-SideTurn-HO-HeadOther-S-Shake-W-Waggle-N-Nod-J-Jerk-HB-HeadBackward-HF-HeadForward--rdXY.svm.9-11-13-middle.tab
F4_F1-all-final2_primary_F4.T-Tilt-ST-SideTurn-HO-HeadOther-S-Shake-W-Waggle-N-Nod-J-Jerk-HB-HeadBackward-HF-HeadForward--rdXY.svm.9-11-13-middle.tab
F5_F2-all-final2_primary_F2.T-Tilt-ST-SideTurn-HO-HeadOther-S-Shake-W-Waggle-N-Nod-J-Jerk-HB-HeadBac

### SKELETON TO READ FILES, SPEAKERS and PRIMARY SPEAKERS


In [23]:
speaker_set = set()

for each_file in glob.glob(PATH+"*.tab"):
    filename=each_file.split("\\")[-1]
    fileinfo=filename.split("-")
    
    primary_speaker = fileinfo[2].split("_")[-1][:-2] #fileinfo[2] = final2_primary_M1.T
    speakers = fileinfo[0]
    l_speaker,r_speaker = speakers.split("_")

    speaker_set.add(primary_speaker)

In [24]:
speaker_set

{'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6'}

### SKELETON TO READ FILES AND COSS_VALIDATE

In the following way: In each iteration, we will leave one speaker out (two files), train a model and test on those two files.

In [25]:

for speaker_on_focus in speaker_set:
    train_files = []
    test_files  = []
    
    for each_file in glob.glob(PATH+"*.tab"):
        filename=each_file.split("\\")[-1]
        fileinfo=filename.split("-")

        primary_speaker = fileinfo[2].split("_")[-1][:-2] #fileinfo[2] = final2_primary_M1.T
        speakers = fileinfo[0]
        l_speaker,r_speaker = speakers.split("_")
        if primary_speaker == l_speaker:
            secondary_speaker = r_speaker
        else:
            secondary_speaker = l_speaker

        #print (primary_speaker,l_speaker,r_speaker,speaker_on_focus)

        file_df = pd.read_csv(each_file,sep="\t")
        file_df.columns = [el.replace(primary_speaker, "PRIMA").replace(secondary_speaker, "SECON") for el in file_df.columns]

        if primary_speaker != speaker_on_focus:
            #FILES TO TRAIN!
            train_files.append(file_df)
        else:
            #FILES TO TEST!
            test_files.append(file_df)
            
        
        
    training_data = pd.concat(train_files, ignore_index=True)
    testing_data = pd.concat(test_files, ignore_index=True)
    print ("Speaker on focus:",speaker_on_focus)
    print ("Training data size:",training_data.shape)
    print ("Testing data size:",testing_data.shape)
    print ()


Speaker on focus: F5
Training data size: (181647, 28)
Testing data size: (16413, 28)

Speaker on focus: M6
Training data size: (181528, 28)
Testing data size: (16532, 28)

Speaker on focus: M4
Training data size: (181548, 28)
Testing data size: (16512, 28)

Speaker on focus: F3
Training data size: (181651, 28)
Testing data size: (16409, 28)

Speaker on focus: M1
Training data size: (180025, 28)
Testing data size: (18035, 28)

Speaker on focus: M5
Training data size: (180649, 28)
Testing data size: (17411, 28)

Speaker on focus: F4
Training data size: (181137, 28)
Testing data size: (16923, 28)

Speaker on focus: M3
Training data size: (181426, 28)
Testing data size: (16634, 28)

Speaker on focus: F1
Training data size: (181919, 28)
Testing data size: (16141, 28)

Speaker on focus: F6
Training data size: (182822, 28)
Testing data size: (15238, 28)

Speaker on focus: M2
Training data size: (182715, 28)
Testing data size: (15345, 28)

Speaker on focus: F2
Training data size: (181593, 28)


### Experiments:

It seems that in the 3-6-9 experiments considering both the past and future of frames, the MLP was not the best model, but the Logistic Regression. I think, though, that the MLP will show good performance when cross-validating with the whole data.

I will, then, try 3 classifiers:

  * SVM, because it is the default classifier that is commonly used
  * Logistic Regression, because it seems to perform the best in our initial experiments with two dialogue data
  * MLP, because when including more data, I expect to estimate a more general (and thus, better) model

In [26]:
accuracy_results = pd.DataFrame(0,columns=speaker_set,index=["MF"])
accuracy_results

F5  M6  M4  F3  M1  M5  F4  M3  F1  F6  M2  F2
MF   0   0   0   0   0   0   0   0   0   0   0   0

In [27]:
import math

def map_movements(mov_class):
    if mov_class == "Nod" or mov_class == "Jerk":
        return 1
    elif mov_class == "Shake":
        return 2
    elif mov_class!=mov_class: #This returns True if the value is NAN, and it works. It might be source of errors.
        return 0
    else:
        return 3



In [28]:
accuracy_results = pd.DataFrame(0,columns=speaker_set,index=["MF"])
f1score_results = pd.DataFrame(0,columns=speaker_set,index=["MF"])
f1score_resultsw = pd.DataFrame(0,columns=speaker_set,index=["MF"])
#f1score_resultsb = pd.DataFrame(0,columns=speaker_set,index=["MF"])
#f1_score(y_true, y_pred, average='micro')

for speaker_on_focus in speaker_set:
    train_files = []
    test_files  = []
    
    for each_file in glob.glob(PATH+"*.tab"):
        filename=each_file.split("\\")[-1]
        fileinfo=filename.split("-")

        primary_speaker = fileinfo[2].split("_")[-1][:-2] #fileinfo[2] = final2_primary_M1.T
        speakers = fileinfo[0]
        l_speaker,r_speaker = speakers.split("_")
        if primary_speaker == l_speaker:
            secondary_speaker = r_speaker
        else:
            secondary_speaker = l_speaker

        #print (primary_speaker,l_speaker,r_speaker,speaker_on_focus)

        file_df = pd.read_csv(each_file,sep="\t")
        file_df.columns = [el.replace(primary_speaker, "PRIMA").replace(secondary_speaker, "SECON") for el in file_df.columns]

        if primary_speaker != speaker_on_focus:
            #FILES TO TRAIN!
            train_files.append(file_df)
        else:
            #FILES TO TEST!
            test_files.append(file_df)
            
        
        
    training_data = pd.concat(train_files, ignore_index=True)
    testing_data = pd.concat(test_files, ignore_index=True)
    print ("Speaker on focus:",speaker_on_focus)
    print ("Training data size:",training_data.shape)
    print ("Testing data size:",testing_data.shape)
    print ()
    
    
    
    
    
    
    
    #Train data
    features=['PRIMA:velocity-r', 'PRIMA:velocity-clock', 'PRIMA:velocity-x', 'PRIMA:velocity-y',
              'PRIMA:acceleration-r', 'PRIMA:acceleration-clock', 'PRIMA:acceleration-x',
              'PRIMA:acceleration-y', 'PRIMA:jerk-r', 'PRIMA:jerk-clock', 'PRIMA:jerk-x', 'PRIMA:jerk-y',
              'PRIMA:pitch', 'PRIMA:intensity'
             ]

    feats_learning = training_data[features]
    X = feats_learning.dropna() #REMEMBER THIS!!!! We're ignoring any row that has a NaN value.
    scaler = MinMaxScaler((0,1))
    scaler.fit(X)
    X_norm = scaler.transform(X)
    #X_norm = X
    #We're ignoring anyrow that has a NaN value.
    Y = (training_data[(feats_learning.isnull().sum(axis=1)==0)]['PRIMA:HeadMovement'].notna()*1).values #0: no movement; 1: movement
    #Y = training_data[(feats_learning.isnull().sum(axis=1)==0)]['PRIMA:HeadMovement'].map(map_movements)
    
    #Test data
    feats_testing = testing_data[features]

    X_test = feats_testing.dropna() #REMEMBER THIS!!!! We're ignoring any row that has a NaN value.
    X_test_norm = scaler.transform(X_test)
    #X_test_norm = X_test
    Y_test = (testing_data[(feats_testing.isnull().sum(axis=1)==0)]['PRIMA:HeadMovement'].notna()*1).values #0: no movement; 1: movement
#    Y_test =  testing_data[(feats_testing.isnull().sum(axis=1)==0)]['PRIMA:HeadMovement'].map(map_movements)
    
    classifiers_to_test = [(DummyClassifier(strategy="most_frequent"),"MF"),
                           (LogisticRegression(solver="liblinear"),"LR"),
                          (LinearSVC(),"LINEARSVC"),
                          (MLPClassifier(hidden_layer_sizes=(30,30,30,30), random_state=442), "MLP")
                          ]
                        #I think that now we have to fine-tune the n_hidden_layers and their sizes (MLP)
    
    
    for clf, clfname in classifiers_to_test:
        print ("Trying classifier ",clfname,speaker_on_focus)
        clf.fit(X_norm, Y)
        y_pred = clf.predict(X_test_norm)
        accuracy_results.loc[clfname,speaker_on_focus] = accuracy_score(Y_test,y_pred)
        #f1score_resultsb.loc[clfname,speaker_on_focus] = f1_score(Y_test,y_pred)
        f1score_results.loc[clfname,speaker_on_focus] = f1_score(Y_test,y_pred, average='macro')
        f1score_resultsw.loc[clfname,speaker_on_focus] = f1_score(Y_test,y_pred, average='weighted')
    
        print (confusion_matrix(Y_test,y_pred))
        print (accuracy_score(Y_test,y_pred)) #same as f1-score (micro-averagaed)
        print (f1_score(Y_test,y_pred, average='macro'))
        print (f1_score(Y_test,y_pred, average='weighted'))
        y_pred=None
        print ()

        
accuracy_results

Speaker on focus: F5
Training data size: (181647, 28)
Testing data size: (16413, 28)

Trying classifier  MF F5


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[[12154     0]
 [ 4259     0]]
0.7405105708889295
0.42545594567157907
0.6301092504347008

Trying classifier  LR F5
[[11421   733]
 [ 3186  1073]]
0.7612258575519405
0.6036945089926578
0.7238829509017742

Trying classifier  LINEARSVC F5
[[11519   635]
 [ 3285   974]]
0.7611649302382258
0.5932793130752054
0.7189746139288845

Trying classifier  MLP F5
[[10958  1196]
 [ 2792  1467]]
0.7570218729056236
0.6349564386290438
0.7364954338469974

Speaker on focus: M6
Training data size: (181528, 28)
Testing data size: (16532, 28)

Trying classifier  MF M6


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[[9316    0]
 [7216    0]]
0.5635131865473022
0.36041473228102755
0.4061969085325493

Trying classifier  LR M6
[[8337  979]
 [4919 2297]]
0.6432373578514397
0.5882801164118258
0.607387766581228

Trying classifier  LINEARSVC M6
[[8418  898]
 [5135 2081]]
0.6350713767239293
0.5722162164179195
0.5930456051890448

Trying classifier  MLP M6
[[7956 1360]
 [3852 3364]]
0.6847326397290104
0.6583752569576407
0.6704289381030841

Speaker on focus: M4
Training data size: (181548, 28)
Testing data size: (16512, 28)

Trying classifier  MF M4


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[[10705     0]
 [ 5807     0]]
0.6483163759689923
0.39332035125105635
0.509992049435872

Trying classifier  LR M4
[[9732  973]
 [3821 1986]]
0.7096656976744186
0.6277443898352804
0.6795453923909347

Trying classifier  LINEARSVC M4
[[9854  851]
 [4026 1781]]
0.7046390503875969
0.611857466724014
0.6681493280871044

Trying classifier  MLP M4
[[9175 1530]
 [3082 2725]]
0.720687984496124
0.6703941182645128
0.7085862666059751

Speaker on focus: F3
Training data size: (181651, 28)
Testing data size: (16409, 28)

Trying classifier  MF F3


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[[9660    0]
 [6749    0]]
0.5887013224449997
0.37055506540335265
0.4362925140832941

Trying classifier  LR F3
[[9173  487]
 [5130 1619]]
0.6576878542263392
0.5656330377391288
0.6011071667825851

Trying classifier  LINEARSVC F3
[[9239  421]
 [5299 1450]]
0.6514108111402279
0.5500218709950717
0.5879141812739971

Trying classifier  MLP F3
[[8821  839]
 [4418 2331]]
0.6796270339447864
0.62021685667444
0.6468644723961624

Speaker on focus: M1
Training data size: (180025, 28)
Testing data size: (18035, 28)

Trying classifier  MF M1


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[[12498     0]
 [ 5537     0]]
0.6929858608261713
0.409327612746864
0.5673164961586146

Trying classifier  LR M1
[[11049  1449]
 [ 3118  2419]]
0.7467701691156086
0.671567012810709
0.7322262446807444

Trying classifier  LINEARSVC M1
[[11247  1251]
 [ 3327  2210]]
0.7461602439700582
0.6610578306211466
0.7266103258432085

Trying classifier  MLP M1


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[10919  1579]
 [ 2778  2759]]
0.7584141946215692
0.6962276789705253
0.7492767396870592

Speaker on focus: M5
Training data size: (180649, 28)
Testing data size: (17411, 28)

Trying classifier  MF M5


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[[9595    0]
 [7816    0]]
0.5510883923956119
0.3552914167222098
0.39159395134680414

Trying classifier  LR M5
[[9283  312]
 [5675 2141]]
0.656136924932514
0.5865716482714043
0.6038996554374801

Trying classifier  LINEARSVC M5
[[9342  253]
 [5861 1955]]
0.6488426856584918
0.5717558527330198
0.5903205577248182

Trying classifier  MLP M5
[[8886  709]
 [4647 3169]]
0.6923783814829705
0.6552032880183406
0.6667713291716687

Speaker on focus: F4
Training data size: (181137, 28)
Testing data size: (16923, 28)

Trying classifier  MF F4


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[[10008     0]
 [ 6915     0]]
0.5913845062932104
0.3716163529018603
0.43953630678270017

Trying classifier  LR F4
[[8900 1108]
 [3031 3884]]
0.755421615552798
0.7318649429610775
0.7463906184647042

Trying classifier  LINEARSVC F4
[[9055  953]
 [3258 3657]]
0.7511670507593217
0.7229819841261125
0.7391317453518472

Trying classifier  MLP F4


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[8217 1791]
 [2346 4569]]
0.7555397979081723
0.7436266127484059
0.7537273478633065

Speaker on focus: M3
Training data size: (181426, 28)
Testing data size: (16634, 28)

Trying classifier  MF M3


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[[11972     0]
 [ 4662     0]]
0.71973067211735
0.41851359854575965
0.6024341471431808

Trying classifier  LR M3
[[10872  1100]
 [ 2913  1749]]
0.7587471444030299
0.6549573211531863
0.7381211497135675

Trying classifier  LINEARSVC M3
[[11025   947]
 [ 3086  1576]]
0.7575447877840568
0.6420349672773904
0.7313964645685039

Trying classifier  MLP M3


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[9821 2151]
 [2024 2638]]
0.7490080557893471
0.6914764235408772
0.7500252515704353

Speaker on focus: F1
Training data size: (181919, 28)
Testing data size: (16141, 28)

Trying classifier  MF F1


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[[10841     0]
 [ 5300     0]]
0.6716436404188092
0.40178637610258694
0.5397145286324446

Trying classifier  LR F1
[[10156   685]
 [ 3007  2293]]
0.7712657208351403
0.700095425828803
0.7502486249423876

Trying classifier  LINEARSVC F1
[[10251   590]
 [ 3180  2120]]
0.7664333064865869
0.687007660579187
0.7411335373437797

Trying classifier  MLP F1
[[9618 1223]
 [2299 3001]]
0.7817979059537823
0.7377193149519556
0.7746302221215371

Speaker on focus: F6
Training data size: (182822, 28)
Testing data size: (15238, 28)

Trying classifier  MF F6


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[[7718    0]
 [7520    0]]
0.5064969156057225
0.33620839867572744
0.34057703385999005

Trying classifier  LR F6
[[6068 1650]
 [2871 4649]]
0.7033075206720042
0.7007121587645083
0.7010743022864845

Trying classifier  LINEARSVC F6
[[6223 1495]
 [3073 4447]]
0.70022312639454
0.696094856959016
0.6965551032136521

Trying classifier  MLP F6
[[5331 2387]
 [2182 5338]]
0.7001575009843811
0.7001574377091964
0.7001556479253987

Speaker on focus: M2
Training data size: (182715, 28)
Testing data size: (15345, 28)

Trying classifier  MF M2


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[[10965     0]
 [ 4380     0]]
0.7145650048875856
0.4167616875712657
0.5956066346326397

Trying classifier  LR M2
[[10539   426]
 [ 3364  1016]]
0.7530140110785272
0.5983081290995916
0.7052847365585112

Trying classifier  LINEARSVC M2
[[10610   355]
 [ 3458   922]]
0.7515151515151515
0.5868244442349357
0.6987658467370229

Trying classifier  MLP M2
[[10152   813]
 [ 2861  1519]]
0.760573476702509
0.6496991903881697
0.7342708543960376

Speaker on focus: F2
Training data size: (181593, 28)
Testing data size: (16467, 28)

Trying classifier  MF F2


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


[[10315     0]
 [ 6152     0]]
0.6264043237991134
0.38514674034799495
0.48251516690223695

Trying classifier  LR F2
[[8757 1558]
 [2635 3517]]
0.7453695269326532
0.7166809225249848
0.7394730332404664

Trying classifier  LINEARSVC F2
[[8961 1354]
 [2828 3324]]
0.7460375296046639
0.7123269449983608
0.7372226632378569

Trying classifier  MLP F2


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[7604 2711]
 [1819 4333]]
0.7249043541628712
0.7136038100941061
0.7279860066573189



F5        M6        M4        F3        M1        M5  \
MF         0.740511  0.563513  0.648316  0.588701  0.692986  0.551088   
LR         0.761226  0.643237  0.709666  0.657688  0.746770  0.656137   
LINEARSVC  0.761165  0.635071  0.704639  0.651411  0.746160  0.648843   
MLP        0.757022  0.684733  0.720688  0.679627  0.758414  0.692378   

                 F4        M3        F1        F6        M2        F2  
MF         0.591385  0.719731  0.671644  0.506497  0.714565  0.626404  
LR         0.755422  0.758747  0.771266  0.703308  0.753014  0.745370  
LINEARSVC  0.751167  0.757545  0.766433  0.700223  0.751515  0.746038  
MLP        0.755540  0.749008  0.781798  0.700158  0.760573  0.724904

In [29]:
accuracy_results

F5        M6        M4        F3        M1        M5  \
MF         0.740511  0.563513  0.648316  0.588701  0.692986  0.551088   
LR         0.761226  0.643237  0.709666  0.657688  0.746770  0.656137   
LINEARSVC  0.761165  0.635071  0.704639  0.651411  0.746160  0.648843   
MLP        0.757022  0.684733  0.720688  0.679627  0.758414  0.692378   

                 F4        M3        F1        F6        M2        F2  
MF         0.591385  0.719731  0.671644  0.506497  0.714565  0.626404  
LR         0.755422  0.758747  0.771266  0.703308  0.753014  0.745370  
LINEARSVC  0.751167  0.757545  0.766433  0.700223  0.751515  0.746038  
MLP        0.755540  0.749008  0.781798  0.700158  0.760573  0.724904

In [30]:
f1score_resultsw

F5        M6        M4        F3        M1        M5  \
MF         0.630109  0.406197  0.509992  0.436293  0.567316  0.391594   
LR         0.723883  0.607388  0.679545  0.601107  0.732226  0.603900   
LINEARSVC  0.718975  0.593046  0.668149  0.587914  0.726610  0.590321   
MLP        0.736495  0.670429  0.708586  0.646864  0.749277  0.666771   

                 F4        M3        F1        F6        M2        F2  
MF         0.439536  0.602434  0.539715  0.340577  0.595607  0.482515  
LR         0.746391  0.738121  0.750249  0.701074  0.705285  0.739473  
LINEARSVC  0.739132  0.731396  0.741134  0.696555  0.698766  0.737223  
MLP        0.753727  0.750025  0.774630  0.700156  0.734271  0.727986

In [31]:
f1score_results

F5        M6        M4        F3        M1        M5  \
MF         0.425456  0.360415  0.393320  0.370555  0.409328  0.355291   
LR         0.603695  0.588280  0.627744  0.565633  0.671567  0.586572   
LINEARSVC  0.593279  0.572216  0.611857  0.550022  0.661058  0.571756   
MLP        0.634956  0.658375  0.670394  0.620217  0.696228  0.655203   

                 F4        M3        F1        F6        M2        F2  
MF         0.371616  0.418514  0.401786  0.336208  0.416762  0.385147  
LR         0.731865  0.654957  0.700095  0.700712  0.598308  0.716681  
LINEARSVC  0.722982  0.642035  0.687008  0.696095  0.586824  0.712327  
MLP        0.743627  0.691476  0.737719  0.700157  0.649699  0.713604

In [32]:
accuracy_results.T.describe()

MF         LR  LINEARSVC        MLP
count  12.000000  12.000000  12.000000  12.000000
mean    0.634612   0.721821   0.718351   0.730404
std     0.075262   0.046450   0.048769   0.034604
min     0.506497   0.643237   0.635071   0.679627
25%     0.582404   0.691903   0.688020   0.698213
50%     0.637360   0.746070   0.746099   0.736956
75%     0.698381   0.756253   0.753023   0.757370
max     0.740511   0.771266   0.766433   0.781798

In [33]:
f1score_results.T.describe()

MF         LR  LINEARSVC        MLP
count  12.000000  12.000000  12.000000  12.000000
mean    0.387033   0.645509   0.633955   0.680971
std     0.028472   0.057792   0.060778   0.039306
min     0.336208   0.565633   0.550022   0.620217
25%     0.368020   0.595801   0.583172   0.653827
50%     0.389234   0.641351   0.626946   0.680935
75%     0.411186   0.700250   0.689279   0.703519
max     0.425456   0.731865   0.722982   0.743627